### ISSUE TITLE
Affichage de la starte carte

### ISSUE THREAD

**Issue by Lithyon** [DevQuestNiort/devquest-website#15]

**Comment by Ithrandil** [comment]
Pour la carte y aller. Mettre une carte en mode Mordor ou vieux parchemin. Chercher open street map, il y a une grosse communauté (exemples https://openmaptiles.org/styles/) https://github.com/openmaptiles/mapbox-studio-woodcut.tm2. https://snazzymaps.com/.

**Comment by Ithrandil** [comment]
FFS finally done
