### ISSUE TITLE
Affichage des partenaires

### ISSUE THREAD

**Issue by Lithyon** [DevQuestNiort/devquest-website#16]

**Comment by Ithrandil** [comment]
Partenaires, garder l’idée de liste mais essayer si possible d’encapsuler comme pour flupa https://uxdays.eu/ ILS ONT DES BONNES IDEES ET METTRE UN PETIT ICON AVEC 3 niveaux collé comme une médaille genre épée diamant fer bois, oeuf de dragon, dragon normal et dragon épique ou un truc dans le genre.paille bois brique etc EN MOBILE EN METTRE DEUX PAR LIGNE

**Comment by nayosis** [comment]
Fini
