### ISSUE TITLE
Mentions Légales

### ISSUE THREAD

**Issue by Lithyon** [DevQuestNiort/devquest-website#20]

**Comment by Ithrandil** [comment]
Idée pour la page mention légales :  mettre ca dans un parchemin pour rester dans le thème.

Possibles sources : Mentions légales https://svgsilh.com/fr/tag/parchemin-1.html

**Comment by Lithyon** [comment]
Pour le contenue idée de réf : https://devfest2023.gdgnantes.com/legal-mentions/
